<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="12" result="Failed" label="Invalid" total="12" passed="2" failed="10" inconclusive="0" skipped="0" asserts="19" engine-version="3.8.0.0" clr-version="4.0.30319.42000" start-time="2018-03-12 22:30:11Z" end-time="2018-03-12 22:30:17Z" duration="6.040016">
  <command-line><![CDATA["E:\AutoTestFramework\ApiTests\SaasApiTests\packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\bin\Debug\ApiTests.dll xml=nunit-result.xml]]></command-line>
  <test-suite type="Assembly" id="1-1013" name="ApiTests.dll" fullname="E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\bin\Debug\ApiTests.dll" runstate="Runnable" testcasecount="12" result="Failed" site="Child" start-time="2018-03-12 22:30:12Z" end-time="2018-03-12 22:30:17Z" duration="4.709342" total="12" passed="2" failed="10" warnings="0" inconclusive="0" skipped="0" asserts="19">
    <environment framework-version="3.9.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.16299.0" platform="Win32NT" cwd="E:\AutoTestFramework\ApiTests\SaasApiTests\packages\NUnit.ConsoleRunner.3.8.0\tools" machine-name="UKRPC029" user="dmytro.petrovskyi" user-domain="ALTIUM" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="E:\AutoTestFramework\ApiTests\SaasApiTests\packages\NUnit.ConsoleRunner.3.8.0\tools" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.6.1" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="28296" />
      <property name="_APPDOMAIN" value="domain-dfb4294b-ApiTests.dll" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="1-1014" name="ApiTests" fullname="ApiTests" runstate="Runnable" testcasecount="12" result="Failed" site="Child" start-time="2018-03-12 22:30:12Z" end-time="2018-03-12 22:30:17Z" duration="4.684194" total="12" passed="2" failed="10" warnings="0" inconclusive="0" skipped="0" asserts="19">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="1-1015" name="tests" fullname="ApiTests.tests" runstate="Runnable" testcasecount="12" result="Failed" site="Child" start-time="2018-03-12 22:30:12Z" end-time="2018-03-12 22:30:17Z" duration="4.683277" total="12" passed="2" failed="10" warnings="0" inconclusive="0" skipped="0" asserts="19">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="1-1000" name="SaasApiTests" fullname="ApiTests.tests.SaasApiTests" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" testcasecount="12" result="Failed" site="Child" start-time="2018-03-12 22:30:12Z" end-time="2018-03-12 22:30:17Z" duration="4.678089" total="12" passed="2" failed="10" warnings="0" inconclusive="0" skipped="0" asserts="19">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="1-1004" name="AddNewContactTest" fullname="ApiTests.tests.SaasApiTests.AddNewContactTest" methodname="AddNewContactTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="332384111" result="Passed" start-time="2018-03-12 22:30:12Z" end-time="2018-03-12 22:30:14Z" duration="1.657298" asserts="4" />
          <test-case id="1-1005" name="ChangeContactTest" fullname="ApiTests.tests.SaasApiTests.ChangeContactTest" methodname="ChangeContactTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="929500020" result="Failed" start-time="2018-03-12 22:30:14Z" end-time="2018-03-12 22:30:14Z" duration="0.308205" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  NotFound
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.ChangeContactTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 80
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  NotFound
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.ChangeContactTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 80
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1012" name="DeleteContactTest" fullname="ApiTests.tests.SaasApiTests.DeleteContactTest" methodname="DeleteContactTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="1209700344" result="Failed" start-time="2018-03-12 22:30:14Z" end-time="2018-03-12 22:30:14Z" duration="0.118231" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  NotFound
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.DeleteContactTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 166
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  NotFound
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.DeleteContactTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 166
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1008" name="EditContactEmailTest" fullname="ApiTests.tests.SaasApiTests.EditContactEmailTest" methodname="EditContactEmailTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="1407003554" result="Failed" start-time="2018-03-12 22:30:14Z" end-time="2018-03-12 22:30:15Z" duration="0.266490" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactEmailTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 117
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactEmailTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 117
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1011" name="EditContactFirstLastNameTest" fullname="ApiTests.tests.SaasApiTests.EditContactFirstLastNameTest" methodname="EditContactFirstLastNameTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="50291849" result="Failed" start-time="2018-03-12 22:30:15Z" end-time="2018-03-12 22:30:15Z" duration="0.224889" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactFirstLastNameTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 155
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactFirstLastNameTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 155
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1009" name="EditContactFirstNameEmailTest" fullname="ApiTests.tests.SaasApiTests.EditContactFirstNameEmailTest" methodname="EditContactFirstNameEmailTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="2101767295" result="Failed" start-time="2018-03-12 22:30:15Z" end-time="2018-03-12 22:30:15Z" duration="0.333130" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactFirstNameEmailTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 129
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactFirstNameEmailTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 129
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1006" name="EditContactFirstNameTest" fullname="ApiTests.tests.SaasApiTests.EditContactFirstNameTest" methodname="EditContactFirstNameTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="1954801472" result="Failed" start-time="2018-03-12 22:30:15Z" end-time="2018-03-12 22:30:15Z" duration="0.329185" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactFirstNameTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 93
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactFirstNameTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 93
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1010" name="EditContactLastNameEmailTest" fullname="ApiTests.tests.SaasApiTests.EditContactLastNameEmailTest" methodname="EditContactLastNameEmailTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="328892749" result="Failed" start-time="2018-03-12 22:30:15Z" end-time="2018-03-12 22:30:16Z" duration="0.330130" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 200
  But was:  InternalServerError
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactLastNameEmailTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 142
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: 200
  But was:  InternalServerError
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactLastNameEmailTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 142
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1007" name="EditContactLastNameTest" fullname="ApiTests.tests.SaasApiTests.EditContactLastNameTest" methodname="EditContactLastNameTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="1067430958" result="Failed" start-time="2018-03-12 22:30:16Z" end-time="2018-03-12 22:30:16Z" duration="0.329278" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactLastNameTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 104
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  InternalServerError
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.EditContactLastNameTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 104
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1001" name="GetApplicationTest" fullname="ApiTests.tests.SaasApiTests.GetApplicationTest" methodname="GetApplicationTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="464821618" result="Failed" start-time="2018-03-12 22:30:16Z" end-time="2018-03-12 22:30:16Z" duration="0.276354" asserts="2">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  200
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.GetApplicationTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 19
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  200
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.GetApplicationTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 19
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1-1003" name="GetContactByIdTest" fullname="ApiTests.tests.SaasApiTests.GetContactByIdTest" methodname="GetContactByIdTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="379255087" result="Passed" start-time="2018-03-12 22:30:16Z" end-time="2018-03-12 22:30:17Z" duration="0.374811" asserts="4" />
          <test-case id="1-1002" name="HealthCheckTest" fullname="ApiTests.tests.SaasApiTests.HealthCheckTest" methodname="HealthCheckTest" classname="ApiTests.tests.SaasApiTests" runstate="Runnable" seed="405031770" result="Failed" start-time="2018-03-12 22:30:17Z" end-time="2018-03-12 22:30:17Z" duration="0.114781" asserts="1">
            <failure>
              <message><![CDATA[  Expected: OK
  But was:  406
]]></message>
              <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.HealthCheckTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 26
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: OK
  But was:  406
]]></message>
                <stack-trace><![CDATA[   at ApiTests.tests.SaasApiTests.HealthCheckTest() in E:\AutoTestFramework\ApiTests\SaasApiTests\ApiTests\tests\SaasApiTests.cs:line 26
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
  <test-suite type="Unknown" id="2-1" name="xml=nunit-result.xml" fullname="E:\AutoTestFramework\ApiTests\SaasApiTests\packages\NUnit.ConsoleRunner.3.8.0\tools\xml=nunit-result.xml" testcasecount="0" runstate="NotRunnable" result="Failed" label="Invalid">
    <properties>
      <property name="_SKIPREASON" value="File not found: E:\AutoTestFramework\ApiTests\SaasApiTests\packages\NUnit.ConsoleRunner.3.8.0\tools\xml=nunit-result.xml" />
    </properties>
    <reason>
      <message>File not found: E:\AutoTestFramework\ApiTests\SaasApiTests\packages\NUnit.ConsoleRunner.3.8.0\tools\xml=nunit-result.xml</message>
    </reason>
  </test-suite>
</test-run>